#######################################
###       Logging Configuration    ###
###            4.15                 ###
#######################################

trial: 'LTH_On_Pretrained_SSL'
notes: 'LTH in SSL Setting higher LR =0.1 for resetting, 6 GPUs, 30 epochs and 25 levels'
model: 'ssl_resnet'
exp_dir: 'experiments'
wand_exp_name: 'LTH_Experiment_4_15'
data_root: 'data'
seed: 123
learning_rate: 0.1
epochs: 30
levels: 18
batch_size: 512
optimiser: 'sgd'
reset_itr: 500
momentum:  0.9
config_file_name: "4_15_lth_ssl.yaml"
early_stop: False
dataset: cifar10
gpus: 6
nodes: 1
max_steps: 30000
swa_enabled: False
prune_global: True
val_freq: 3
es_patience: 5
es_delta: 0.01
pruning_amt: 0.2



