#######################################
###       Logging Configuration    ###
###            4.4                 ###
#######################################
# Taken from 14/42 https://arxiv.org/pdf/1803.03635.pdf
trial: 'LTH_Early_Stop'
model: 'resnet18'
notes: 'Measure Early Stopping Use a high LR Vary the delta, Validation freq set'
exp_dir: 'experiments'
wand_exp_name: 'LTH_Experiment_4_4'
data_root: 'data'
seed: 123
learning_rate: 0.1
epochs: 40
levels: 20
batch_size: 128
optimiser: 'sgd'
reset_itr: 500
momentum:  0.9
config_file_name: "4_4_lth_es.yaml"
early_stop: True
dataset: cifar10
gpus: 6
nodes: 1
max_steps: 30000
swa_enabled: False
prune_global: True
val_freq: 2
es_patience: 5
es_delta: 0.01
pruning_amt: 0.2


