#######################################
###       Logging Configuration    ###
###                                ###
#######################################
# Running the model on Lightning https://pytorchlightning.github.io/lightning-tutorials/notebooks/lightning_examples/cifar10-baseline.html
trial: 'Baseline'
model: 'torch_resnet'
exp_dir: 'experiments'
wand_exp_name: 'Basic_Lightning'
data_root: 'data'
seed: 123
learning_rate: 0.1
epochs: 86
batch_size: 128
optimiser: 'sgd'
momentum:  0.9
config_file_name: "basic_lightning.yaml"
early_stop: False
dataset: cifar10
gpus: 2
nodes: 1
max_steps: 30000
swa_enabled: False
prune_global: True


